name: dash_mement
description: DDD7_dash_project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  google_maps_flutter: ^2.1.5
  geolocator: ^8.2.1
  dio: ^4.0.0
  connectivity_plus: ^1.0.7
  location: ^4.3.0
  permission_handler: ^8.1.4+2
  flutter_svg: ^0.22.0
  provider: ^6.0.0
  fluster: ^1.2.0
  cached_network_image: ^3.1.0
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^8.0.8
  sliding_up_panel: ^2.0.0+1

flutter:

  uses-material-design: true
  assets:
    - assets/styles/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
